
name: 立创oshwhub自动签到

on:
    workflow_dispatch:
    schedule:
        - cron: "1 16,17,18 * * *"
    watch:
        types: [started]

jobs:
    build:
        runs-on: ubuntu-latest
        if: github.event.repository.owner.id == github.event.sender.id
        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: "Set up Python"
              uses: actions/setup-python@v2
              with:
                python-version: 3.8

            - name: "安装依赖包"
              run: pip install -r ./requirements.txt

            - name: "运行 立创oshwhub自动签到"
              run: python3 ./oshwhub_autosign.py
              env:
                  oshw: ${{ secrets.oshw }}
